# =========================================================
# Email HITL Notifier
#
# Sends SMTP alerts with Approve / Deny hyperlinks
# embedded in the body.  Falls back to simulation when
# SMTP is not configured.
# =========================================================

from __future__ import annotations

import logging
import smtplib
from email.message import EmailMessage
from typing import Iterable, List, Optional

from agentic_v2_platform.config.settings import get_settings

logger = logging.getLogger(__name__)


def _split_recipients(value: str) -> List[str]:
    return [r.strip() for r in str(value or "").replace(";", ",").split(",") if r.strip()]


# =========================================================
# HITL EMAIL
# =========================================================

def send_hitl_email(
    *,
    approval_id: str,
    ticket_key: str,
    db_alias: str,
    summary: str,
    recommendation: str,
    risk_level: str,
    approve_url: str,
    deny_url: str,
    recipients: Optional[Iterable[str]] = None,
) -> bool:
    """
    Send an approval-request email with clickable Approve/Deny links.
    """
    cfg = get_settings().notifications
    to_list = list(recipients or _split_recipients(cfg.smtp_to))
    subject = f"[DBA HITL] Action Required — {ticket_key} ({risk_level} Risk)"

    body_text = f"""
DBA Platform — Human-in-the-Loop Approval Request
===================================================

Ticket      : {ticket_key}
Database    : {db_alias}
Risk Level  : {risk_level}
Approval ID : {approval_id}

Summary:
{summary}

Recommended Action:
{recommendation}

Please review the recommendation and take one of the following actions:

  APPROVE: {approve_url}?id={approval_id}
  DENY   : {deny_url}?id={approval_id}

NOTE: The database execution layer is strictly isolated.
      No changes will be made until you click APPROVE.

This is an automated message from the AI DBA Operations Platform V2.
"""

    body_html = f"""
<html><body style="font-family:Arial,sans-serif;font-size:14px;">
<h2 style="color:#0078D7;">🔔 DBA Action Required — {ticket_key}</h2>
<table border="0" cellpadding="6" style="border-collapse:collapse;">
  <tr><td><b>Ticket</b></td><td>{ticket_key}</td></tr>
  <tr><td><b>Database</b></td><td>{db_alias}</td></tr>
  <tr><td><b>Risk Level</b></td><td style="color:red;"><b>{risk_level}</b></td></tr>
  <tr><td><b>Approval ID</b></td><td>{approval_id}</td></tr>
</table>
<h3>Summary</h3>
<p>{summary}</p>
<h3>Recommended Action</h3>
<p>{recommendation}</p>
<hr/>
<p>
  <a href="{approve_url}?id={approval_id}"
     style="background:#28a745;color:white;padding:10px 20px;
            text-decoration:none;border-radius:4px;margin-right:10px;">
     ✅ APPROVE
  </a>
  &nbsp;
  <a href="{deny_url}?id={approval_id}"
     style="background:#dc3545;color:white;padding:10px 20px;
            text-decoration:none;border-radius:4px;">
     ❌ DENY
  </a>
</p>
<p style="color:#888;font-size:12px;">
  No changes will be applied until APPROVE is clicked.
  This message was generated by AI DBA Operations Platform V2.
</p>
</body></html>
"""
    return _send(subject, body_text, body_html, to_list, cfg)


# =========================================================
# GENERIC ALERT EMAIL
# =========================================================

def send_email_alert(
    subject: str,
    message: str,
    recipients: Optional[Iterable[str]] = None,
) -> bool:
    """Plain-text alert email."""
    cfg = get_settings().notifications
    to_list = list(recipients or _split_recipients(cfg.smtp_to))
    return _send(subject, message, None, to_list, cfg)


# =========================================================
# INTERNAL SEND
# =========================================================

def _send(
    subject: str,
    body_text: str,
    body_html: Optional[str],
    to_list: List[str],
    cfg,
) -> bool:
    if not cfg.smtp_host or not to_list:
        _simulate(subject, body_text, reason="SMTP_HOST or SMTP_TO not configured")
        return False

    msg = EmailMessage()
    msg["Subject"] = subject
    msg["From"] = cfg.smtp_from
    msg["To"] = ", ".join(to_list)
    msg.set_content(body_text)
    if body_html:
        msg.add_alternative(body_html, subtype="html")

    try:
        with smtplib.SMTP(cfg.smtp_host, cfg.smtp_port, timeout=20) as server:
            if cfg.smtp_use_tls:
                server.starttls()
            if cfg.smtp_username and cfg.smtp_password:
                server.login(cfg.smtp_username, cfg.smtp_password)
            server.send_message(msg)
        logger.info("Email sent to %s: %s", to_list, subject)
        return True
    except Exception as exc:
        logger.error("Email send failed: %s", exc)
        return False


def _simulate(subject: str, body: str, reason: str) -> None:
    logger.warning("EMAIL SIMULATION — %s", reason)
    print("\n" + "=" * 60)
    print(" EMAIL NOTIFICATION — SIMULATION MODE")
    print("=" * 60)
    print(f"Reason  : {reason}")
    print(f"Subject : {subject}")
    print(body[:500])
    print("=" * 60 + "\n")
